---
- name: Installing EPEL repo...
  yum: name=epel-release state=installed
  when: ansible_os_family == "RedHat"


- name: Instaling yum plugins...
  yum: name=yum-axelget state=installed update_cache=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Installing Playbook YUM deps...
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
  - libselinux-python
  - python-devel
  - python-pip
  - pyOpenSSL
  when: ansible_os_family == "RedHat"

- name: Install common utilites via apt...
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
    DEBCONF_NONINTERACTIVE_SEEN: true
  apt: name={{ item }} state=present
  with_items: "{{ common_utils_apt }}"
  when: ansible_os_family == "Debian"

- name: Ensure /var/www exist...
  file: state=directory dest=/var/www mode=0755
  tags:
  - mkdir-www

