---
- name: apply sysctl
  shell: sysctl -p /etc/sysctl.conf
  ignore_errors: true

- name: restore iptables
  shell: iptables-restore < /etc/sysconfig/iptables

- name: restore iptables-persistent
  shell: iptables-restore < /etc/iptables/rules.v4