---
- name: Ubuntu 16.04 workarounds
  gather_facts: no
  connection: local
  hosts: all
  tasks:
  - name: Installing Python...
    shell: "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root {{ ansible_ssh_host }} 'apt-get clean ; apt-get update ; apt-get -y install python python-dev python-pip python-simplejson'"
    when: ubuntu_1604 | default(False)
    tags: always

- name: Auth host setup...
  gather_facts: yes
  become_user: root
  hosts: all
  roles:
    - role: common
      tags: common

    - role: auth
      git_repo: https://github.com/itsumma/isolate.git
      git_branch: develop
      deploy_path: /opt/auth
      tags: auth
